### ISSUE TITLE
Project Name Change?

### ISSUE THREAD

**Issue by nelsonic** [nelsonic/sendemail#18]
Given that this module will be 100% generic and thus useable by *any* node.js framework,
should we consider changing the name to something a bit more generic?

<img width="897" alt="npm-sendemail-404" src="https://cloud.githubusercontent.com/assets/194400/10630565/4a72872e-77cf-11e5-9ca0-2c6779cb67d8.png">

**Comment by iteles** [comment]
👍🏻👍🏻

**Comment by iteles** [comment]
Here's the image you were looking for for this project: http://www.randomlolz.com/wp-content/uploads/2011/12/Email-vs-Mail-10-Years-Ago-vs-Now.jpg

**Comment by nelsonic** [comment]
![email-me-again](https://tctechcrunch2011.files.wordpress.com/2014/02/91a939c9d77645f0f3bc32d1fcc0bcf95c6b62118e7299bc705fb2317d4ddffa.jpg)

**Comment by iteles** [comment]
Aggressive :grimacing:

**Comment by nelsonic** [comment]
No. I can *totally* identify with people who receive a lot (*too much!*) email!!
